"""
Django settings for lumina_project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xs!o#@r*2%ck$krowzvt7mtczmxzt339jjfefej9nr89rfwf_p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

# The INSTALLED_APPS list is like a registry or a "membership list" for your project.
# Every piece of functionality (apps) that you want Django to use must be listed here.
# If you don't list an app here, Django won't even know it exists, like a store 
# that isn't listed in a mall's directory.
INSTALLED_APPS = [
    'django.contrib.admin', # This provides the built-in admin interface to manage your data easily.
    'django.contrib.auth',  # This handles user authentication, like logging in and out.
    'django.contrib.contenttypes', # This helps Django track all the different types of models you create.
    'django.contrib.sessions', # This allows Django to remember users as they move from page to page.
    'django.contrib.messages', # This lets you send "flash messages" (like a quick "Saved!" notification) to users.
    'django.contrib.staticfiles', # This helps Django manage images, CSS, and JavaScript files.
    
    # We manually add 'rest_framework' to this list.
    # Django REST Framework is a powerful toolkit that sits on top of Django 
    # and gives it "superpowers" for building APIs (Application Programming Interfaces).
    # Analogy: It's like adding a professional translation kit to a standard phone 
    # so it can talk to many different languages (other apps) instantly.
    'rest_framework', 
    
    # We also add 'quotes', which is the specific app we just created.
    # This is where we will write all our code for the Lumina project.
    # Analogy: This is like opening your own specific shop in the Django mall 
    # and making sure the mall manager (Django) knows you're open for business.
    'quotes', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lumina_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lumina_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
